#!/usr/bin/env bash
#Bash script that transfers a file from our client to a server:

PATH_TO_FILE="${1}"
IP="${2}"
USERNAME="${3}"
PATH_TO_SSH_KEY="${4}"

if [ "$#" -eq 4 ]
then
        scp -i "${PATH_TO_SSH_KEY}" -o StrictHostKeyChecking=no "${PATH_TO_FILE}"  "${USERNAME}"@"${IP}":~/
else
        echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
fi
