#!/usr/bin/env bash
#Install nginx web server

sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx
sudo service nginx start
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
new_redirect="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name _;/$new_redirect/" /etc/nginx/sites-available/default
sudo service nginx restart
