#!/usr/bin/env bash
#Bash script with create and deletes files handle signals
echo "$$" > /var/run/myscript.pid
trap "echo 'I hate the kill command'; rm -f /var/run/myscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm -f /var/run/myscript.pid; exit" SIGQUIT
i=1
while [ $i -gt 0 ];
do
	echo "To infinity and beyond";
	sleep 2;
done
