#!/usr/bin/env bash
# Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.

IFS=":"

while read -r USERNAME PASSWD UID_ GID UID_INFO HOMEDIR COMMAND;
do
	echo "The user ${USERNAME} is part of the ${GID} gang, lives in ${HOMEDIR} and rides ${COMMAND}. ${UID_}'s place is protected by the passcode ${PASSWD}, more info about the user here: ${UID_INFO}"

done < "/etc/passwd"
