#!/usr/bin/env bash
# This script run Nginx as Nginx to prevent the impact is limited by the permissions of the nginx user
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sed -i 's/80 default/8080 default/' /etc/nginx/sites-available/default
sudo -u nginx service nginx stop
sudo -u nginx service nginx start
